// apps/react-demo/src/Checkbox.tsx
export interface CheckboxProps {
  checked: boolean;
  onChange: (checked: boolean) => void;
  label: string;
}

export function Checkbox(props: CheckboxProps) {
  return (
    <label className="checkbox">
      <input
        value={props.checked + ""}
        onInput={() => props.onChange(!props.checked)}
        type="checkbox"
      />

      <span>{props.label}</span>
    </label>
  );
}

// apps/vue-demo/src/Checkbox.vue
<template>
  <label class="checkbox">
    <input
      v-model="model"
      type="checkbox"
    />

    <span>{{ label }}</span>
  </label>
</template>

<script setup lang="ts">
export interface CheckboxProps {
  label: string;
}

defineProps<CheckboxProps>();
const model = defineModel<boolean>();
</script>
