// apps/react-demo/src/CompositeImage.tsx
import multicolorPrimaryImageSrc from "@/assets/recipes/multicolor/primary.svg?set-current-color";
import multicolorSecondaryImageSrc from "@/assets/recipes/multicolor/secondary.svg?set-current-color";
import multicolorTertiaryImageSrc from "@/assets/recipes/multicolor/tertiary.svg?set-current-color";

import "./CompositeImage.scss";

import { SvgImage } from "vite-awesome-svg-loader/react-integration";

export interface CompositeImageProps {
  primary?: string;
  secondary?: string;
  tertiary?: string;
}

export function CompositeImage({ primary, secondary, tertiary }: CompositeImageProps) {
  return (
    <div className="image composite-image">
      <SvgImage
        src={multicolorPrimaryImageSrc}
        style={{ color: primary || "red" }}
      />

      <SvgImage
        src={multicolorSecondaryImageSrc}
        style={{ color: secondary || "blue" }}
      />

      <SvgImage
        src={multicolorTertiaryImageSrc}
        style={{ color: tertiary || "green" }}
      />
    </div>
  );
}

// apps/vue-demo/src/CompositeImage.vue
<template>
  <div class="image composite-image">
    <SvgImage
      :src="multicolorPrimaryImageSrc"
      :style="{ color: primary }"
    />

    <SvgImage
      :src="multicolorSecondaryImageSrc"
      :style="{ color: secondary }"
    />

    <SvgImage
      :src="multicolorTertiaryImageSrc"
      :style="{ color: tertiary }"
    />
  </div>
</template>

<script setup lang="ts">
import multicolorPrimaryImageSrc from "@/assets/recipes/multicolor/primary.svg?set-current-color";
import multicolorSecondaryImageSrc from "@/assets/recipes/multicolor/secondary.svg?set-current-color";
import multicolorTertiaryImageSrc from "@/assets/recipes/multicolor/tertiary.svg?set-current-color";
import { SvgImage } from "vite-awesome-svg-loader/vue-integration";

export interface CompositeImageProps {
  primary?: string;
  secondary?: string;
  tertiary?: string;
}

withDefaults(defineProps<CompositeImageProps>(), {
  primary: "red",
  secondary: "blue",
  tertiary: "green",
});
</script>

<style lang="scss" scoped>
// Overlay images with positions hack
.composite-image {
  position: relative;

  & > :deep(*) {
    position: absolute;
  }
}
</style>
